
@startuml FinanceTrackApp

skinparam style strictuml
skinparam classAttributeIconSize 0

package "model.account" {
  interface AccountInterface
  enum AccounType
  class Account
}

package "model.transaction" {
  class AbstractTransaction
  class IncomeTransaction
  class ExpenseTransaction
  class MovementTransaction
  class TransactionBuilder
  enum TransactionType
}

package "model.user" {
  class User
  enum Gender
}

package "model.iterator" {
  interface TransactionIterator
  class ConcreteTransactionIterator
}

package "model.composite" {
  class TransactionList
  interface CompositeTransaction
}

package "factory" {
  interface TransactionCreator
  class TransactionFactory
  class IncomeTransactionCreator
  class ExpenseTransactionCreator
  class MovementTransactionCreator
  interface TransactionAbstractFactory
  interface FinanceAbstractFactory
  class DefaultFinanceFactory
  class AccountFactory
}

package "io" {
  interface CsvSerializable
  interface ImporterI
  interface WriterI
  class CsvImporter
  class CsvWriter
}

package "mapper" {
  class UserMapper
  class UserSnapshot
}

package "memento" {
  class UserMementoManager
}

package "service" {
  class BaseService
  class UserService
  class AccountService
  class TransactionService
  class FileIOService
  class MementoService
}

package "clicontroller" {
  interface MenuCliController
  class MainMenuCliController
  class AccountMenuCliController
  class TransactionMenuCliController
  class CsvMenuCliController
  class UserMenuCliController
}

package "utility" {
  class InputSanitizer
  class ConsoleStyle
  class ConsoleUtils
  class TransactionPrinter
}

package "logging" {
  class LoggerFactory
}

package "exception" {
  class AccountOperationException
  class DataValidationException
  class FileIOException
  class LoggingException
  class MementoException
  class TransactionOperationException
  class UserCancelledException
  class UserLoginException
}

@enduml

package "Pattern: Factory" <<Rectangle>> {
  class TransactionFactory
  class TransactionCreator
  class IncomeTransactionCreator
  class ExpenseTransactionCreator
  class MovementTransactionCreator
}

package "Pattern: Abstract Factory" <<Rectangle>> {
  class FinanceAbstractFactory
  class DefaultFinanceFactory
}

package "Pattern: Strategy" <<Rectangle>> {
  class TransactionCreator
  class IncomeTransactionCreator
  class ExpenseTransactionCreator
  class MovementTransactionCreator
}

package "Pattern: Composite" <<Rectangle>> {
  class TransactionList
  class AbstractTransaction
}

package "Pattern: Iterator" <<Rectangle>> {
  class TransactionIterator
  class ConcreteTransactionIterator
}

package "Pattern: Memento" <<Rectangle>> {
  class UserSnapshot
  class UserMapper
  class MementoService
  class UserMementoManager
}

package "Pattern: Singleton" <<Rectangle>> {
  class LoggerFactory
}
